=== KanishkT123/KineticTypography/ChiasmusEngineCLCF_15.04/dtd/alreadyFound.dtd
<?xml version="1.0" encoding="utf-8"?>

<!ELEMENT alreadyFound (category+) >
<!ATTLIST alreadyFound geneFrom CDATA "" >
<!ATTLIST category name ID #REQUIRED>
<!ELEMENT category (chiasm+) >
<!ELEMENT chiasm (wA,wB,extract,context)>
<!ELEMENT wA (#PCDATA) >
<!ATTLIST wA iA CDATA #REQUIRED >
<!ATTLIST wA iD CDATA #REQUIRED >
<!ELEMENT wB (#PCDATA) >
<!ATTLIST wB iB CDATA #REQUIRED >
<!ATTLIST wB iC CDATA #REQUIRED >
<!ELEMENT extract (#PCDATA) >
<!ELEMENT context (#PCDATA) >

=== KanishkT123/KineticTypography/ChiasmusEngineCLCF_15.04/Results/alreadyFound_Eval.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE alreadyFound  SYSTEM 'dtd/alreadyFound.dtd'><alreadyFound geneFrom="140814aSv80001to160000_modif"><category name="good"><chiasm>
			<wA iA="1074472" iD="1074489">Portugal</wA>
			<wB iB="1074479" iC="1074482">Spain</wB>
			<extract>Portugal has no rivers that flow into Spain , but Spain does have rivers that flow into Portugal</extract>
			<context>, in other words , Portugal has no rivers that flow into Spain , but Spain does have rivers that flow into Portugal . Furthermore , when</context>
		</chiasm><chiasm>
			<wA iA="1660536" iD="1660554">European</wA>
			<wB iB="1660542" iC="1660548">national</wB>
			<extract>European political parties took part in national elections , rather than having national political parties take part in European</extract>
			<context>would be appropriate if the European political parties took part in national elections , rather than having national political parties take part in European elections . Europe is</context>
		</chiasm><chiasm>
			<wA iA="1705340" iD="1705356">national</wA>
			<wB iB="1705347" iC="1705350">European</wB>
			<extract>national parliamentarians appearing more regularly in the European Parliament and European parliamentarians more regularly in the national</extract>
			<context>. What is to prevent national parliamentarians appearing more regularly in the European Parliament and European parliamentarians more regularly in the national parliaments ? The requirements</context>
		</chiasm><chiasm>
			<wA iA="2158938" iD="2158952">protected</wA>
			<wB iB="2158943" iC="2158947">unprotected</wB>
			<extract>protected companies can take over unprotected ones , yet unprotected companies cannot take over protected</extract>
			<context>entrenches a situation in which protected companies can take over unprotected ones , yet unprotected companies cannot take over protected ones . This means</context>
		</chiasm><chiasm>
			<wA iA="1381248" iD="1381257">beginning</wA>
			<wB iB="1381251" iC="1381254">end</wB>
			<extract>beginning of the end but the end of the beginning</extract>
			<context>agreement , is not the beginning of the end but the end of the beginning . As my friend</context>
		</chiasm><chiasm>
			<wA iA="552199" iD="552208">state</wA>
			<wB iB="552202" iC="552205">market</wB>
			<extract>State and less market or more market and less State</extract>
			<context>or liberal State ? More State and less market or more market and less State ? There has been</context>
		</chiasm><chiasm>
			<wA iA="1839232" iD="1839238">chicken</wA>
			<wB iB="1839234" iC="1839236">pig</wB>
			<extract>chickens to pigs and pigs to chickens</extract>
			<context>. She wants to feed chickens to pigs and pigs to chickens . I know that</context>
		</chiasm><chiasm>
			<wA iA="552570" iD="552593">Eurosceptics</wA>
			<wB iB="552580" iC="552586">federalist</wB>
			<extract>Eurosceptics are in favour of the Treaty of Nice because federalists protest against it . Some federalists are in favour of it because Eurosceptics</extract>
			<context>. Mr President , some Eurosceptics are in favour of the Treaty of Nice because federalists protest against it . Some federalists are in favour of it because Eurosceptics are opposed to it</context>
		</chiasm><chiasm>
			<wA iA="475514" iD="475530">company</wA>
			<wB iB="475517" iC="475527">railway</wB>
			<extract>company to the railway and once the destination is reached , from the railway to the company</extract>
			<context>sending their products from the company to the railway and once the destination is reached , from the railway to the company . Unless this is</context>
		</chiasm><chiasm>
			<wA iA="1787183" iD="1787191">work</wA>
			<wB iB="1787185" iC="1787189">people</wB>
			<extract>work to people that to take people to work</extract>
			<context>is much better to bring work to people that to take people to work . But it is</context>
		</chiasm><chiasm>
			<wA iA="1574226" iD="1574238">enemy</wA>
			<wB iB="1574229" iC="1574235">friend</wB>
			<extract>enemy is my friend , but my enemy 's friend is my enemy</extract>
			<context>adage that my enemy 's enemy is my friend , but my enemy 's friend is my enemy . If we are</context>
		</chiasm><chiasm>
			<wA iA="50926" iD="50938">dope</wA>
			<wB iB="50929" iC="50932">sport</wB>
			<extract>doping is changing sport and that sport will be changed due to doping</extract>
			<context>There is no doubt that doping is changing sport and that sport will be changed due to doping , which means it</context>
		</chiasm><chiasm>
			<wA iA="1807467" iD="1807483">animal</wA>
			<wB iB="1807475" iC="1807479">environment</wB>
			<extract>animals were no longer adapted to suit their environment , but the environment to suit the animals</extract>
			<context>It is high time that animals were no longer adapted to suit their environment , but the environment to suit the animals . Drastic improvements are</context>
		</chiasm><chiasm>
			<wA iA="818826" iD="818836">Europe</wA>
			<wB iB="818829" iC="818833">Member</wB>
			<extract>Europe following the Member States or of Member States following Europe</extract>
			<context>not be a matter of Europe following the Member States or of Member States following Europe . The much-discussed internal</context>
		</chiasm><chiasm>
			<wA iA="1824593" iD="1824601">food</wA>
			<wB iB="1824597" iC="1824599">medicine</wB>
			<extract>food should be our medicine and medicine our food</extract>
			<context>ago , Hippocrates said that food should be our medicine and medicine our food . I believe his</context>
		</chiasm><chiasm>
			<wA iA="1702033" iD="1702053">Research</wA>
			<wB iB="1702040" iC="1702045">Framework</wB>
			<extract>Research Area is not simply the European Framework Programme . The European Framework Programme is an aspect of the European Research</extract>
			<context>once again that the European Research Area is not simply the European Framework Programme . The European Framework Programme is an aspect of the European Research Area . The European</context>
		</chiasm><chiasm>
			<wA iA="2060420" iD="2060432">solution</wA>
			<wB iB="2060426" iC="2060429">problem</wB>
			<extract>solution because this is an international problem and international problems require international solutions</extract>
			<context>are calling for an international solution because this is an international problem and international problems require international solutions . We are here</context>
		</chiasm><chiasm>
			<wA iA="1975881" iD="1975892">thing</wA>
			<wB iB="1975885" iC="1975890">change</wB>
			<extract>things that we cannot change , enough determination to change the things</extract>
			<context>the courage to accept the things that we cannot change , enough determination to change the things that we can change</context>
		</chiasm><chiasm>
			<wA iA="218980" iD="218995">policy</wA>
			<wB iB="218983" iC="218988">region</wB>
			<extract>policies to these regions instead of expecting the regions to adapt to an elitist European policy</extract>
			<context>we should adapt the Community policies to these regions instead of expecting the regions to adapt to an elitist European policy . What is ...</context>
		</chiasm></category><category name="goodelse"><chiasm><wA iA="1975880" iD="1975898">the</wA><wB iB="1975885" iC="1975890">change</wB><extract>the things that we cannot change , enough determination to change the things that we can change and the</extract><context>: the courage to accept the things that we cannot change , enough determination to change the things that we can change and the wisdom to know the</context></chiasm><chiasm><wA iA="1975878" iD="1975900">to</wA><wB iB="1975885" iC="1975890">change</wB><extract>to accept the things that we cannot change , enough determination to change the things that we can change and the wisdom to</extract><context>three things : the courage to accept the things that we cannot change , enough determination to change the things that we can change and the wisdom to know the difference between</context></chiasm><chiasm><wA iA="1975876" iD="1975898">the</wA><wB iB="1975885" iC="1975890">change</wB><extract>the courage to accept the things that we cannot change , enough determination to change the things that we can change and the</extract><context>we need three things : the courage to accept the things that we cannot change , enough determination to change the things that we can change and the wisdom to know the</context></chiasm><chiasm>
			<wA iA="1574225" iD="1574234">'s</wA>
			<wB iB="1574226" iC="1574233">enemy</wB>
			<extract>'s enemy is my friend , but my enemy 's</extract>
			<context>old adage that my enemy 's enemy is my friend , but my enemy 's friend is my enemy</context>
		</chiasm><chiasm>
			<wA iA="50928" iD="50935">change</wA>
			<wB iB="50929" iC="50932">sport</wB>
			<extract>changing sport and that sport will be changed</extract>
			<context>no doubt that doping is changing sport and that sport will be changed due to doping ,</context>
		</chiasm><chiasm>
			<wA iA="1074475" iD="1074485">river</wA>
			<wB iB="1074479" iC="1074482">Spain</wB>
			<extract>rivers that flow into Spain , but Spain does have rivers</extract>
			<context>words , Portugal has no rivers that flow into Spain , but Spain does have rivers that flow into Portugal</context>
		</chiasm><chiasm>
			<wA iA="50926" iD="50938">dope</wA>
			<wB iB="50928" iC="50935">change</wB>
			<extract>doping is changing sport and that sport will be changed due to doping</extract>
			<context>There is no doubt that doping is changing sport and that sport will be changed due to doping , which means it</context>
		</chiasm><chiasm>
			<wA iA="1074477" iD="1074487">flow</wA>
			<wB iB="1074479" iC="1074482">Spain</wB>
			<extract>flow into Spain , but Spain does have rivers that flow</extract>
